title: .NET project file analyzers
description: Contains roslyn static code analyzers to analyze .NET project files. 
url: https://dotnet-project-file-analyzers.github.io/

remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
- jekyll-remote-theme
- jekyll-default-layout
- jekyll-seo-tag
- jekyll-github-metadata
- jekyll-include-cache
- jekyll-sitemap

markdown: GFM

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  ignore:
    envs: all
