global using DotNetProjectFile.Diagnostics;
global using Microsoft.CodeAnalysis;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Threading;
