global using DotNetProjectFile.Analyzers.Helpers;
global using DotNetProjectFile.Caching;
global using DotNetProjectFile.Diagnostics;
global using DotNetProjectFile.IO;
global using DotNetProjectFile.MsBuild;
global using DotNetProjectFile.Xml;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.Diagnostics;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Diagnostics.Contracts;
global using System.Linq;
global using System.Threading;
global using System.Xml.Linq;
global using MsBuildProject = DotNetProjectFile.MsBuild.Project;
global using ProjectFileAnalysisContext = DotNetProjectFile.Diagnostics.ProjectFileAnalysisContext<DotNetProjectFile.MsBuild.Project>;
global using ResourceFileAnalysisContext = DotNetProjectFile.Diagnostics.ProjectFileAnalysisContext<DotNetProjectFile.Resx.Resource>;
