global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Linq;
global using System.Threading;
global using System.Xml.Linq;
global using DotNetProjectFile.Analyzers.Helpers;
global using DotNetProjectFile.Caching;
global using DotNetProjectFile.Diagnostics;
global using DotNetProjectFile.IO;
global using DotNetProjectFile.MsBuild;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.Diagnostics;
global using MsBuildProject = DotNetProjectFile.MsBuild.Project;
