global using CodeAnalysis.TestTools;
global using DotNetProjectFile.Analyzers;
global using DotNetProjectFile.Analyzers.MsBuild;
global using FluentAssertions;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.Diagnostics;
global using NUnit.Framework;
global using System.Diagnostics.Contracts;
global using System.Text;
global using Resx = DotNetProjectFile.Analyzers.Resx;
