global using CodeAnalysis.TestTools;
global using DotNetProjectFile.Analyzers;
global using DotNetProjectFile.Analyzers.MsBuild;
global using FluentAssertions;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.Diagnostics;
global using NUnit.Framework;
global using System;
global using System.Collections.Generic;
global using System.Diagnostics.Contracts;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Resx = DotNetProjectFile.Analyzers.Resx;
